platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: demo-app-source-code
outputs:
  - name: artifacts

run:
  path: "demo-app-source-code/ci/tasks/package.sh"

params:
  MAVEN_BASEDIR: demo-app-source-code
