platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk

inputs:
  - name: demo-app-source-code
outputs:
  - name: artifacts

run:
  path: "demo-app-source-code/ci/tasks/package.sh"

params:
  MAVEN_BASEDIR: demo-app-source-code
